#!/bin/sh

csgo_pid=$(pidof csgo_linux64)
if [ -z "$csgo_pid" ]; then
    /bin/echo -e "\e[31mCSGO needs to be open before you can inject...\e[0m"
    exit 1
fi

if [ ! -d ".git" ]; then
    /bin/echo "We have detected that you have downloaded ayytux-master.zip from the GitHub website. This is the WRONG way to download AyyTux. Please download AimTux with the command 'git clone --recursive https://github.com/GreenByteSoftware/AyyTux'"
fi

# pBypass paste for crash dumps being sent
sudo rm -rf /tmp/dumps # Remove if it's there
sudo mkdir /tmp/dumps # Make it as root
sudo chmod 000 /tmp/dumps # No permissions

#Credit: Aixxe @ aixxe.net
if grep -q libAyyTux.so /proc/$csgo_pid/maps; then
    /bin/echo -e "\e[33mAyyTux is already injected... Aborting...\e[0m"
    exit
fi

input="$(
sudo gdb -n -q -batch \
  -ex "attach $csgo_pid" \
  -ex "set \$dlopen = (void*(*)(char*, int)) dlopen" \
  -ex "call \$dlopen(\"$(pwd)/libAyyTux.so\", 1)" \
  -ex "detach" \
  -ex "quit"
)"

last_line="${input##*$'\n'}"

if [ "$last_line" != "\$1 = (void *) 0x0" ]; then
    /bin/echo -e "\e[32mSuccessfully injected!\e[0m"
else
    /bin/echo -e "\e[31mInjection failed, make sure you've compiled...\e[0m"
fi
